### ISSUE TITLE
Switch to Live Environment? 

### ISSUE THREAD

**Issue by ddavisgraphics** [paypal/Checkout-Ruby-SDK#11]
I was reading the documentation and looking at setting this up for an app we already have in production.  

This configuration appears to set up the sandbox environment.  
```ruby
require 'paypal-sdk-rest'
environment = PayPal::SandboxEnvironment.new('your_client_id', 'your_client_secret')
client = PayPal::PayPalHttpClient.new(environment)
```

What sets up the live environment so that you can begin processing payments?  I'm curious because the documentation doesn't mention anything about switching to live, I found in the code the environment change --> https://github.com/paypal/Checkout-Ruby-SDK/blob/master/lib/core/paypal_environment.rb#L33-L37, but was worried that there would be some other changes to consider for security.  

I'm interested in the beta because my client is worried that he will have to pay me twice for the same intergrations after the first one is deprecated.  Which is a fair concern on his part and until he gains more funding there isn't really wiggle room in his budget.

**Comment by rajarampadmanathan** [comment]
Hi....Switching SandboxEnvironment with LiveEnvironment should work.  No more changes required.

**Comment by ddavisgraphics** [comment]
Thank you.
