### ISSUE TITLE
Typo in developer docs.

### ISSUE THREAD

**Issue by imgarylai** [paypal/Checkout-Ruby-SDK#16]
There is a typo in the developer documents. 

The typo is in the ruby example under the [Set up the environment](
https://developer.paypal.com/docs/checkout/reference/server-integration/setup-sdk/#set-up-the-environment).

```diff
require 'paypal-checkout-sdk'

module PayPalClient
  class << self

    # Set up and return PayPal Ruby SDK environment with PayPal access credentials.
-   # This sample uses SandboxEnvironment. In production, use ProductionEnvironment.
+   # This sample uses SandboxEnvironment. In production, use LiveEnvironment.
...
```

**Comment by ganeshramc** [comment]
Hey @imgarylai  this update should go up on the public docs next week. Thanks for contributing!

**Comment by michaelcarter** [comment]
@ganeshramc This tripped us up and caused several lost bookings in a new PayPal integration. Does it really need to wait 10+ days to be fixed?

**Comment by ganeshramc** [comment]
@michaelcarter, I apologize. We follow a 2 week cycle for updates to documentation and our next release to goes live next week. We'll definitely keep your feedback in mind.

**Comment by ganeshramc** [comment]
Hey @michaelcarter and @imgarylai, this was updated last week. Thanks again for your patience!
