### ISSUE TITLE
New RubyGems release

### ISSUE THREAD

**Issue by Xanders** [paypal/Checkout-Ruby-SDK#18]
Hello!

Thank you for the gem. :)

Can you please release new gem version with [expires_in](https://github.com/paypal/Checkout-Ruby-SDK/commit/f8c8f23615b3bd5b78ef1d3644baa51c089a2d68) fix? This gem is pretty unusable without that fix since it stops to process orders after several hours of work.

We now use reference to commit in Gemfile as a workaround, but it seems to be better to use official RubyGems release in production.

**Comment by numbata** [comment]
@ganeshramc Have you any scheduled date for the new release?

**Comment by Xanders** [comment]
At fact, version with expires_in fix was released at November 18, 2019:
https://rubygems.org/gems/paypal-checkout-sdk/versions/1.0.3

So I think I can close this issue now.
