### ISSUE TITLE
Support for Invoice API /v2/invoicing

### ISSUE THREAD

**Issue by puneetpandey** [paypal/Checkout-Ruby-SDK#25]
Hi,
We are using PayPal's invoicing API through `paypal-sdk-rest` gem (https://github.com/paypal/PayPal-Ruby-SDK). I came across Checkout-Ruby-SDK because `/v1/invoices` is as deprecated by PayPal and we are planning to upgrade to `/v2/invoicing`. Does this gem supports `/v2/invoicing`?

**Comment by rsdighe76** [comment]
No this SDK doesn't support v2/invoicing
